services:
  - type: web
    name: agrovision-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python run.py
    plan: free
    envVars:
      - key: PORT
        value: 8000
